Sprint2
Dr-mmnt/RA-SPRINT pull request #3
Opened 2023-04-06 12:24 UTC by Dr-mmnt

2023-04-09 17:08 UTC, euge-huge requested changes
Работа хорошая!

Есть небольшие замечания.
Адаптив реализован, декомпозиция и возможности scss использованы, есть, что можно улучшить. 
 
Есть вопросы к форматированию кода, к наличию лишних пустых строк, отступов и тд. Посмотри сочетание клавиш в VS Code, которое правит форматирование кода.

Молодец, продолжай в том же духе!

2023-04-09 17:08 UTC, euge-huge commented on src/index.html
> +          </section>
Пока лишний блок для этого спринта затесался)

2023-04-09 17:08 UTC, euge-huge commented on src/scss/_common.scss
Нужно отформатировать немного код, отуступы, между блоками - одна пустая строка

2023-04-09 17:08 UTC, euge-huge commented on src/scss/_mixins.scss
`отлично`

Это хорошо сделано и удобно использовать, молодец!

2023-04-09 17:08 UTC, euge-huge commented on src/scss/_mobile.scss
> +@media only screen and (max-width: 992px) {
`нужно поправить`

Я бы выбрал что-то одно.

Либо использовать mixins, либо вот так делать, отдельно

2023-04-09 17:08 UTC, euge-huge commented on src/scss/main.scss
> +
Пустые строки :)

2023-04-09 17:08 UTC, euge-huge commented on src/scss/main.scss
> +  $button-color: #fb9475;
`нужно поправить`

Переменные внутри блока так не нужно объявлять.

Нужно создать отдельный файл тогда, где будут лежать все эти переменные. Проверь по всему файлу, вынеси все в отдельный файл

2023-04-09 17:08 UTC, euge-huge commented on src/scss/main.scss
> +    }
`нужно поправить`

Очевидный пример БЭМодификатора.

Его пишем как:
&_active {}

2023-04-09 17:08 UTC, euge-huge commented on src/scss/main.scss
> +  margin-top: 100px;
`нужно поправить` `ко всему файлу`

Внешнюю геометрию у блоков задавать нельзя по БЭМ, это нужно делать только у элементов.

2023-04-09 17:08 UTC, euge-huge commented on src/scss/main.scss
> +}
Почему бы не вложить этот код в блок выше?

2023-04-09 17:08 UTC, euge-huge commented on src/scss/main.scss
> +    }
Это тоже модификатор, поправить нейминг.

2023-04-09 17:08 UTC, euge-huge commented on src/scss/main.scss
> +  }
Модификатор.

2023-04-09 17:08 UTC, euge-huge commented on src/scss/main.scss
> +}
Лого разве к header не относится? Если относится, то можно внести во внутрь.

2023-04-10 15:27 UTC, Dr-mmnt commented on src/scss/main.scss
> +  }
Это значит надо переписать &_column?

2023-04-13 14:42 UTC, euge-huge approved these changes

2023-05-07 18:21 UTC, merged